
paytm_credentials:
  staging:
    mid: "VSBEGC70642255300673"
    merchant_key: "bdXPMfHFWeF%lCLW"
    industry_type_id: "Retail"
    txn_status_url: "https://securegw-stage.paytm.in/order/status"
    app:
      website: "WEBSTAGING"
      channel_id: "WEB"
    web:
      website: "WEBSTAGING"
      channel_id: "WEB"
      payment_url: "https://securegw-stage.paytm.in/order/process"
      callback_url: "http://localhost:3000/payment_response"
  production:
    mid: "Fill"
    merchant_key: "Fill"
    industry_type_id: "Fill"
    txn_status_url: "https://secure.paytm.in/oltp/HANDLER_INTERNAL/getTxnStatus FIll this"
    app:
      website: "FIll THis"
      channel_id: "FIll This"
    web:
      website: ""
      channel_id: "FIll THis"
      payment_url: "FIll THis"
      callback_url: "http://localhost:3000/order-processed"
